### ISSUE TITLE
Image Distortion - Possible IOS issue

### ISSUE THREAD

**Issue by jawa-the-hutt** [luwes/js-cover-flow#21]
I'm struggling with understanding if the issue I'm seeing is an issue with js-cover-flow or an issue with IOS that is causing images to be distorted.  I don't have an android device to test with.  I've been able to reproduce this issue on IOS 6.1.3 and 7.0.  However, an iPad I had running 5.1.1 did not reproduce the issue.

I have a page that will allow a user to take a picture or upload a picture from their iPhone/iPad.  Once the picture is uploaded, it will insert the picture into the coverflow.  

-- If I take the picture or upload from the device's photo library with an iPhone, the image gets distorted, but the iPhone will display pictures taken with the iPad normally.

-- If I take a picture or upload from the device's photo library with the iPad, the picture does not get distorted, but the iPad will display images taken by the iPhone in the distorted manner. 

-- If I upload a picture from my desktop (doesn't matter if it's IE. FF, or Chrome) then the picture is displayed normally.  To top it off, pictures taken with the iPhone that display distorted on the iPhone or iPad will display normally in the desktop browser.

Here is what it looks like from a Desktop Browser:

![desktop](https://f.cloud.github.com/assets/1318561/1231753/dae02f4a-286d-11e3-9f8e-082ac684e3b2.png)

Here is what it looks like from an iPhone or iPad running IOS 6.x and above.  The last picture on the right was taken from the iPad.

![ios](https://f.cloud.github.com/assets/1318561/1231766/8d9f5110-286e-11e3-8f9d-991570fc1b64.PNG)

I'm leaning towards this being an IOS issue, but I don't know enough about how the plugin operates to say for sure.

**Comment by luwes** [comment]
Thanks for the contributions. I guess this can be closed now. 
It was only affecting cover images > 1.5Mb.
