### ISSUE TITLE
using <a> tag instead of window.open

### ISSUE THREAD

**Issue by tolgacanatan** [luwes/js-cover-flow#34]
windows.open blocked by some browsers. Why we use html a tag for the 'link'?

**Comment by luwes** [comment]
`window.open` is blocked sometimes when it is called **later** (most likely an ajax call) than the user interacting with the UI. It can be solved following these steps:

1. call window.open just before calling $.ajax and save window reference:  
`var newWindow = window.open(...);`
2. on callback set location property of the saved window reference:  
`newWindow.location = url;`
